### PR TITLE
Added spectrogram generation with SoX

### PR DESCRIPTION
**Pull request by MilesBHuff**
You can automatically generate spectrograms by using SoX.  I went ahead and added a line to the `test.sh` script that does exactly that.

### CODE REVIEW

**Comment by Lastique** [comment]
Please, make it so that SoX is only used when it's installed (i.e. `sox` is present). You can test result of `type sox` for that. Also, no need for explicitly running it from `/usr/bin`, just run it unqualified.

**Comment by MilesBHuff** [comment]
Sure, I'll add a check for that.
I only did `/usr/bin` because you did on the line above (for `time`), and I wanted to keep things consistent.
I'll revise the pull request in a bit.

**Comment by Lastique** [comment]
I explicitly qualified `/usr/bin/time` because `time` is a built-in bash command with a different behavior.

**Comment by MilesBHuff** [comment]
The more you know.
Btw, if you call `/usr/bin/env time`, then `time` will honor the user's `PATH`.
Also, if you do `[[ $(which sox) = *:* ]]` instead of `[[ -f /usr/bin/sox ]]`, then `sox` won't fail to run if it's not in `/usr/bin/` when it is on the `PATH`.
UPDATE:  Unfortunately, not all versions of `which` have a `:` in their "found" messages;  so I ended up using `[[ -f /usr/bin/sox ]]` after-all.
RETRO:  I forgot about your `type` idea.  That would have been a great solution.

**Comment by MilesBHuff** [comment]
I went ahead and refactored the whole script.  I need to test this before you merge.  I will reply again when I have tested.  Please do not merge until then.
(I will not be able to test this until tonight (EDT) at the earliest.)

**Comment by MilesBHuff** [comment]
Finally got around to testing it, and committed the necessary post-test fixes.
@Lastique Is it ready for merging now?  Or is there anything else you'd like me to change?

**Comment by Lastique** [comment]
Merged with corrections, thanks.

**Pull request merged**
